package com.github.zheniatrochun.exceptions

case object UserAlreadyExistsException extends Exception("Such user is already exists!")
